# Generated by Django 3.2 on 2021-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
