# Generated by Django 3.2 on 2021-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=240, null=True, unique=True),
        ),
    ]
