# Generated by Django 3.2 on 2021-04-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_created',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
